name: Sincronizar Projeto Descompactado com o Google Drive

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o código do repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Envia os arquivos soltos/descompactados para o Drive
      - name: Enviar arquivos soltos
        uses: marcosvilela/google-drive-upload@v1.0.3
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          folderId: ${{ secrets.DRIVE_FOLDER_ID }}
          # Indica que você quer enviar a raiz do projeto e manter a estrutura de pastas
          targetPath: '.' 
