name: Sincronizar Projeto com o Google Drive

on:
  push:
    branches:
      - main    # Altere para 'master' se o seu repositório usar o nome antigo da branch principal
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Baixa o código do seu repositório do GitHub para o servidor da Action
      - name: Checkout do código
        uses: actions/checkout@v4

      # Passo 2: Faz o upload dos arquivos diretamente para a pasta do Google Drive
      - name: Enviar arquivos para o Google Drive
        uses: adityassarkar/webdav-upload@v2
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          folder_id: ${{ secrets.DRIVE_FOLDER_ID }}
          # Define que a raiz do repositório será enviada
          cloud_path: '.' 
